"""
build_index.py

Generates an index of all published lessons.

This script scans the published/ directory and creates an index.md
listing every released lesson with links.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

CONTENT_DIR = ROOT / "content"
PUBLISHED_DIR = ROOT / "published"

SYLLABUS_FILE = CONTENT_DIR / "syllabus.json"
INDEX_FILE = PUBLISHED_DIR / "index.md"


def load_syllabus() -> dict[int, dict]:
    """
    Load syllabus.json and return a dictionary
    keyed by lesson day.
    """
    if not SYLLABUS_FILE.exists():
        return {}

    with SYLLABUS_FILE.open("r", encoding="utf-8") as file:
        data = json.load(file)

    return {lesson["day"]: lesson for lesson in data}


def get_published_days() -> list[int]:
    """
    Return a sorted list of published lesson numbers.
    """
    if not PUBLISHED_DIR.exists():
        return []

    days = []

    for folder in PUBLISHED_DIR.iterdir():
        if not folder.is_dir():
            continue

        if folder.name.startswith("Day"):
            try:
                days.append(int(folder.name[3:]))
            except ValueError:
                continue

    return sorted(days)


def build_index() -> str:
    """
    Generate the Markdown lesson index.
    """
    syllabus = load_syllabus()
    published_days = get_published_days()

    lines = [
        "# 📚 Published Lessons",
        "",
        "> This file is automatically generated by the Python 365 publishing engine.",
        "",
        f"**Published Lessons:** {len(published_days)}",
        "",
        "| Day | Topic | Module |",
        "|-----|-------|--------|",
    ]

    if not published_days:
        lines.append("| - | No lessons published yet | - |")
    else:
        for day in published_days:
            lesson = syllabus.get(day, {})

            title = lesson.get("title", f"Day {day}")
            module = lesson.get("module", "Unknown")

            folder = f"Day{day:03d}"

            lines.append(
                f"| [{folder}](./{folder}/README.md) | {title} | {module} |"
            )

    lines.extend(
        [
            "",
            "---",
            "",
            f"Generated automatically by **Python 365**.",
        ]
    )

    return "\n".join(lines)


def save_index() -> None:
    """
    Generate and save the published lesson index.
    """
    PUBLISHED_DIR.mkdir(parents=True, exist_ok=True)

    INDEX_FILE.write_text(
        build_index(),
        encoding="utf-8",
    )


def main() -> None:
    save_index()
    print("✅ Published lesson index generated successfully.")


if __name__ == "__main__":
    main()
